# Generated by Django 3.2 on 2023-06-02 04:55

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название тэга')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[recipes.validators.validate_regex], verbose_name='Слэг тэга')),
                ('color', models.CharField(default='#E26C2D', max_length=7, unique=True, verbose_name='Цвет(HEX)')),
            ],
            options={
                'verbose_name': 'Тэг',
                'ordering': ('id',),
            },
        ),
    ]
