# Generated by Django 3.2 on 2023-06-11 09:53

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='name',
            field=models.CharField(help_text='Уникальное название, не более 200 символов', max_length=200, validators=[recipes.validators.validate_name()], verbose_name='Название ингредиента'),
        ),
    ]
