# Generated by Django 3.2 on 2023-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follow_subscribe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_follow',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='cant_follow_yourself',
        ),
    ]
